services:
  - type: web
    name: MyBooksStatistics
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    numInstances: 1
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 3000
